# Generated by Django 5.0.7 on 2024-07-29 10:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=12000)),
                ('bot_message', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 7, 29, 10, 41, 56, 844908, tzinfo=datetime.timezone.utc))),
                ('created_for', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 7, 29, 10, 41, 56, 845908, tzinfo=datetime.timezone.utc))),
                ('created_for', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=300)),
                ('email', models.CharField(default='', max_length=300)),
                ('uid', models.CharField(default='', max_length=300)),
                ('messages', models.ManyToManyField(to='chat_bot_app.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=300)),
                ('lead_email', models.CharField(default='', max_length=300)),
                ('color_code', models.CharField(default='', max_length=300)),
                ('website_url', models.CharField(default='', max_length=300)),
                ('logo_url', models.CharField(default='', max_length=300)),
                ('subscription_model', models.CharField(default='', max_length=300)),
                ('chatbot_url', models.CharField(default='', max_length=300)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(default='', max_length=300)),
                ('assistant_id', models.CharField(default='', max_length=300)),
                ('vector_store_id', models.CharField(default='', max_length=300)),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot_app.customer')),
            ],
        ),
    ]
