# Generated by Django 5.1 on 2024-09-14 08:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(default="", max_length=12000)),
                ("bot_message", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 9, 14, 8, 41, 40, 437247, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 9, 14, 8, 41, 40, 436841, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="SummariserAssistant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assistant_id", models.CharField(default="", max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="ChatbotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 9, 14, 8, 41, 40, 437888, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                ("name", models.CharField(default="", max_length=300)),
                ("email", models.CharField(default="", max_length=300)),
                ("uid", models.CharField(default="", max_length=300)),
                ("lead_processed", models.BooleanField(default=False)),
                ("messages", models.ManyToManyField(to="chat_bot_app.chatmessage")),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(default="", max_length=300)),
                ("lead_email", models.CharField(default="", max_length=300)),
                ("color_code", models.CharField(default="", max_length=300)),
                ("accent_color", models.CharField(default="", max_length=300)),
                ("website_url", models.CharField(default="", max_length=300)),
                ("logo_url", models.CharField(default="", max_length=300)),
                ("subscription_model", models.CharField(default="", max_length=300)),
                ("chatbot_url", models.CharField(default="", max_length=300)),
                ("js_url", models.CharField(default="", max_length=300)),
                ("css_url", models.CharField(default="", max_length=300)),
                ("save_user_data_url", models.CharField(default="", max_length=300)),
                ("send_message_url", models.CharField(default="", max_length=300)),
                ("training_file_path", models.CharField(default="", max_length=300)),
                ("code", models.TextField(default="", max_length=8000)),
                ("css_code", models.TextField(default="", max_length=16000)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatFineTuneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_name", models.CharField(default="", max_length=300)),
                ("fine_tuned_model_id", models.CharField(default="", max_length=300)),
                (
                    "created_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat_bot_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatAssistant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_name", models.CharField(default="", max_length=300)),
                ("assistant_id", models.CharField(default="", max_length=300)),
                ("vector_store_id", models.CharField(default="", max_length=300)),
                (
                    "created_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat_bot_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(default="", max_length=8000)),
                ("answer", models.CharField(default="", max_length=8000)),
                (
                    "created_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat_bot_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Themengebiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("themenbereich", models.CharField(max_length=1155)),
                ("amount", models.PositiveIntegerField(default=1)),
                (
                    "created_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat_bot_app.customer",
                    ),
                ),
            ],
        ),
    ]
