# Generated by Django 5.0.7 on 2024-07-30 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotuser',
            name='lead_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 9, 11, 59, 562927, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 9, 11, 59, 561927, tzinfo=datetime.timezone.utc)),
        ),
    ]
