# Generated by Django 5.0.7 on 2024-07-30 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot_app', '0002_chatbotuser_lead_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 7, 30, 9, 56, 0, 387789, tzinfo=datetime.timezone.utc))),
                ('created_for', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 9, 56, 0, 387789, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 9, 56, 0, 386790, tzinfo=datetime.timezone.utc)),
        ),
    ]
