# Generated by Django 5.0.7 on 2024-08-09 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot_app', '0004_alter_chatbotuser_created_at_alter_lead_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummariserAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_id', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 6, 53, 38, 600004, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 6, 53, 38, 599004, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 6, 53, 38, 599004, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='themengebiet',
            name='themenbereich',
            field=models.CharField(max_length=1155),
        ),
    ]
