# Generated by Django 5.0.7 on 2024-08-09 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot_app', '0006_customer_accent_color_alter_chatbotuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='css_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='customer',
            name='js_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='customer',
            name='save_user_data_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='customer',
            name='send_message_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 9, 15, 58, 617880, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 9, 15, 58, 617880, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 9, 15, 58, 617880, tzinfo=datetime.timezone.utc)),
        ),
    ]
