# Generated by Django 5.0.7 on 2024-08-21 09:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot_app', '0007_customer_css_url_customer_js_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 9, 2, 37, 311718, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 9, 2, 37, 311718, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 9, 2, 37, 311718, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=8000)),
                ('answer', models.CharField(default='', max_length=8000)),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot_app.customer')),
            ],
        ),
    ]
