# Generated by Django 5.0.7 on 2024-08-21 09:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot_app', '0008_alter_chatbotuser_created_at_alter_lead_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 9, 44, 42, 513440, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 9, 44, 42, 513440, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 9, 44, 42, 513440, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ChatFineTuneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(default='', max_length=300)),
                ('fine_tuned_model_id', models.CharField(default='', max_length=300)),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot_app.customer')),
            ],
        ),
    ]
