# Generated by Django 5.0.7 on 2024-08-21 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot_app', '0010_remove_customer_website_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='website_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 9, 45, 50, 339393, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 9, 45, 50, 339393, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 9, 45, 50, 338394, tzinfo=datetime.timezone.utc)),
        ),
    ]
