# Generated by Django 5.0.7 on 2024-08-22 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot_app', '0012_customer_code_alter_chatbotuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 15, 29, 25, 229935, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 15, 29, 25, 229935, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 15, 29, 25, 229935, tzinfo=datetime.timezone.utc)),
        ),
    ]
